### ISSUE TITLE
Plugin shows "Please select a vector"

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [c5inco/shape-composer-figma#1]
<img src="https://i.imgur.com/4U3Tm0A.gif" width="1000" />

As the preview above shows as well, when I'm trying to export a shape using this plugin, Figma shows a message like `Please select a vector 🙈`.

I just wanted to ask if there's anything I am getting wrong or if I could provide some more information about the issue? Is there some way for me to get the logs that could help you or something?

The current device I'm using is a MacBook Pro M1 14" and the browser I'm using this plugin on is Google Chrome.

**Comment by c5inco** [comment]
A Rectangle is technically not a vector object in Figma. You'll have to convert it manually for now. 

Also FWIW this plugin isn't designed to convert Rectangles to Shape classes in Jetpack Compose since that shape already exists in the system. The plugin is intended to help export more complex, custom shapes beyond Rectangle and Circle, like squircles, bottlecaps, clovers, etc.

**Comment by c5inco** [comment]
If you are running into issues with a more complex shape, simply share the Figma file with me and I'll try to repro the issue on my side.

**Comment by shubhamsinghmutualmobile** [comment]
@c5inco Thanks for the quick reply first of all. And secondly, as shown below, I tried a complex shape as well (which is not available by default in Compose), but it still shows the same message. Also linking the figma file for your ref.

https://www.figma.com/file/Qve8XFP3crX5NYqzF2zrkj/ComposeShapeTest?node-id=0%3A1
<img src="https://imgur.com/tl92XkV.gif" width="1000"/>

**Comment by shubhamsinghmutualmobile** [comment]
I also tried creating a vector using the PEN TOOL. In this case, the plugin doesn't show the message anymore, but it opens up a window (as shown in the preview) that doesn't seem to provide any information or do anything. Only the close button works on that window. Figma link is the same as in the comment above.

Demo: https://imgur.com/ziIitEv.gif
<img src="https://media.giphy.com/media/rN2ILQi9Z9dVviRdau/giphy.gif" width="1000" />

**Comment by c5inco** [comment]
>I'm using this plugin on is Google Chrome.

This is actually the issue. There's [inconsistencies](https://forum.figma.com/t/write-to-clipboard-from-custom-plugin/11860/) in the Figma API around browser copy/paste commands, so this plugin works best in the desktop app. This is noted on the plugin download page as well.

As for the Polygon issue, that is still a Polygon shape in your file. You will have to flatten it to be a Vector. Usually I do this by copying it and flattening it, to not destroy the original in case I want to modify the shape. I've considered looking into cloning and flattening it via the plugin using the Figma APIs but wasn't sure if that is desirable for folks since everyone manages their files differently.

**Comment by shubhamsinghmutualmobile** [comment]
@c5inco Thank you! Like you suggested, it is now working on Figma Desktop after flattening the shapes 🙌🏻 🚀

**Comment by shubhamsinghshubham777** [comment]
@c5inco Thank you! Like you suggested, the plugin is working perfectly on Figma Desktop after I flatten the shapes 🙌🏻 🚀
